//! Truly cross-panel primitives and minimal reusable components.

use makepad_widgets::*;

pub mod activity_header;
pub mod activity_loader;
pub mod auth_row;
pub mod capability_row;
pub mod chat_bubble;
pub mod clipped_label;
pub mod code_label;
pub mod command_input;
pub mod composer_action;
pub mod composer_surface;
pub mod context_menu;
pub mod context_window;
pub mod empty_row;
pub mod file_tree;
pub mod flex_spacer;
pub mod git_changes;
pub mod git_diff;
pub mod header_chip;
pub mod icon_button;
pub mod init;
pub mod modal_dialog;
pub mod model_dropdown;
pub mod nav_button;
pub mod notice_banner;
pub mod panel_header;
pub mod panel_surface;
pub mod provider_card;
pub mod search_input;
pub mod section_header;
pub mod session_row;
pub mod settings_action_button;
pub mod sidebar_compose_button;
pub mod status_dot;
pub mod status_pill;
pub mod starter_prompt_card;
pub mod task_sidebar;
pub mod terminal_panel;
pub mod tool_fold_header;
pub mod tool_section;

pub fn script_mod(vm: &mut ScriptVm) -> ScriptValue {
    init::script_mod(vm);
    icon_button::script_mod(vm);
    clipped_label::script_mod(vm);
    code_label::script_mod(vm);
    status_dot::script_mod(vm);
    notice_banner::script_mod(vm);
    section_header::script_mod(vm);
    activity_header::script_mod(vm);
    activity_loader::script_mod(vm);
    auth_row::script_mod(vm);
    chat_bubble::script_mod(vm);
    capability_row::script_mod(vm);
    header_chip::script_mod(vm);
    command_input::script_mod(vm);
    composer_action::script_mod(vm);
    composer_surface::script_mod(vm);
    context_menu::script_mod(vm);
    context_window::script_mod(vm);
    empty_row::script_mod(vm);
    modal_dialog::script_mod(vm);
    search_input::script_mod(vm);
    flex_spacer::script_mod(vm);
    model_dropdown::script_mod(vm);
    nav_button::script_mod(vm);
    file_tree::script_mod(vm);
    git_changes::script_mod(vm);
    git_diff::script_mod(vm);
    panel_header::script_mod(vm);
    panel_surface::script_mod(vm);
    provider_card::script_mod(vm);
    sidebar_compose_button::script_mod(vm);
    session_row::script_mod(vm);
    settings_action_button::script_mod(vm);
    status_pill::script_mod(vm);
    starter_prompt_card::script_mod(vm);
    task_sidebar::script_mod(vm);
    terminal_panel::script_mod(vm);
    tool_section::script_mod(vm)
}
